### PR TITLE
Pipeline through predictions

### PR DESCRIPTION
**Pull request by PrinceWalnut**
This is the current pipeline up through predictions. We should merge this now while it's stable before we start on integration code.

### CODE REVIEW

**Comment by kmdalton** [comment]
It's going to take me  bit to work through this. My first thought is that it is time that we moved the test data outside of this repository. I'm thinking we could make a Zenodo entry with
 - mccd images
 - ii files
 - inp files
 - anything else you think is appropriate

Then you can just instruct your setup script to download the files.

**Comment by kmdalton** [comment]
I cloned your experimental branch and am following the `INSTRUCTIONS.txt`. I have a lot of comments on usability stuff, but I'm going to just focus on things that are actually broken for now. I don't want us to get bogged down. 

Trying to run `pipeline.sh`
 1) the first `dials.import` call in `scan_varying_indexer.sh` fails because `./dials_temp_files` does not exist. it is not created by the setup scripts, and it isn't in the repo by default. 
 2) bypassing (1) by creating `dials_temp_files`, `dials.find_spots` fails [here](https://github.com/Hekstra-Lab/laue-index-assigner/blob/4af08824fa7f10599663dec87430052062d2b39e/scan_varying_indexer.sh#L26), because the mask file isn't found. 
 3) prediction fails if you don't have `rs` installed in your `cctbx.python`. add instructions for installing it in your INSTRUCTIONS.txt

**Comment by kmdalton** [comment]
You should probably get rid of the hardcoded paths:
```bash
(careless) kmdalton@pop-os:~/opt/laue-index-assigner$ grep -r rahewitt
diagnostic/plot_centroids.py:expt_file = "/n/home04/rahewitt/laue_indexer/laue-index-assigner/dials_temp_files/ultra_refined.expt" # <-- Fill this in 
diagnostic/plot_centroids.py:refl_file = "/n/home04/rahewitt/laue_indexer/laue-index-assigner/dials_temp_files/ultra_refined.refl" # <-- Fill this in 
```

I can help you write a parser in argparse if you want.

**Comment by PrinceWalnut** [comment]
I've resolved the issues you brought up here (and will continue if you find more). 

As for the data, I agree an external place to put the data would be good now. mccd, ii, inp, and a pixels.mask file are all we should need to run this pipeline. Zenodo or any other place is fine with me -- what's your judgment on that? 

Personally, I keep my files in a `$HOME/data` directory (with each dataset getting its own subdirectory) locally. If you want to upload the DHFR data somewhere, I can make a utility script to download the data from that spot and run.

**Review by kmdalton — APPROVED** [review]
Let's go ahead and merge this now. Let's not wait this long between PRs in the future. Afterward, please upload data to Zenodo as we discussed (see #12).

**Pull request merged**
